[package]
name = "rustp"
version = "0.1.0"
authors = ["d0ku <darthtyranus666666@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.1.2"
